// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TrainingArchitect.Core.Models;

public class WeekDataDto
{
    [JsonPropertyName("schema_version")]
    public string SchemaVersion { get; set; } = string.Empty;

    [JsonPropertyName("week_starting")]
    public string WeekStarting { get; set; } = string.Empty;

    [JsonPropertyName("current_date")]
    public string CurrentDate { get; set; } = string.Empty;

    [JsonPropertyName("metrics")]
    public MetricsDto? Metrics { get; set; }

    [JsonPropertyName("week_summary")]
    public WeekSummaryDto? WeekSummary { get; set; }

    [JsonPropertyName("activities")]
    public List<ActivityDto>? Activities { get; set; }

    [JsonPropertyName("fueling_analysis")]
    public FuelingAnalysisDto? FuelingAnalysis { get; set; }

    [JsonPropertyName("planned_workouts")]
    public PlannedWorkoutsDto? PlannedWorkouts { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class ActivityDto
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("duration_hours")]
    public double? DurationHours { get; set; }

    [JsonPropertyName("training_load")]
    public double? TrainingLoad { get; set; }

    [JsonPropertyName("avg_power")]
    public double? AvgPower { get; set; }

    [JsonPropertyName("norm_power")]
    public double? NormPower { get; set; }

    [JsonPropertyName("avg_hr")]
    public double? AvgHr { get; set; }

    [JsonPropertyName("max_hr")]
    public double? MaxHr { get; set; }

    [JsonPropertyName("polarization_index")]
    public double? PolarizationIndex { get; set; }

    [JsonPropertyName("training_distribution")]
    public string? TrainingDistribution { get; set; }

    [JsonPropertyName("training_distribution_reason")]
    public string? TrainingDistributionReason { get; set; }

    [JsonPropertyName("z1_z2_pct")]
    public double? Z1Z2Pct { get; set; }

    [JsonPropertyName("z3_z4_pct")]
    public double? Z3Z4Pct { get; set; }

    [JsonPropertyName("z5_plus_pct")]
    public double? Z5PlusPct { get; set; }

    [JsonPropertyName("interval_summary")]
    public List<string>? IntervalSummary { get; set; }

    [JsonPropertyName("interval_segments")]
    public List<IntervalSegmentDto>? IntervalSegments { get; set; }

    [JsonPropertyName("decoupling")]
    public double? Decoupling { get; set; }

    [JsonPropertyName("decoupling_label")]
    public string? DecouplingLabel { get; set; }

    [JsonPropertyName("rpe")]
    public double? Rpe { get; set; }

    [JsonPropertyName("carbs_used_g")]
    public double? CarbsUsedG { get; set; }

    [JsonPropertyName("carbs_ingested_g")]
    public double? CarbsIngestedG { get; set; }

    [JsonPropertyName("w_prime_j")]
    public double? WPrimeJ { get; set; }

    [JsonPropertyName("w_prime_bal_drop_j")]
    public double? WPrimeBalDropJ { get; set; }

    [JsonPropertyName("w_prime_bal_min_j")]
    public double? WPrimeBalMinJ { get; set; }

    [JsonPropertyName("w_prime_usage_pct")]
    public double? WPrimeUsagePct { get; set; }

    [JsonPropertyName("tags")]
    public List<string>? Tags { get; set; }

    [JsonPropertyName("notes")]
    public string? Notes { get; set; }

    [JsonPropertyName("weather")]
    public WeatherDto? Weather { get; set; }

    [JsonPropertyName("power_curve")]
    public Dictionary<string, double>? PowerCurve { get; set; }

    [JsonPropertyName("wbal_summary")]
    public ActivityWbalSummaryDto? WbalSummary { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class ActivityWbalSummaryDto
{
    [JsonPropertyName("wbal_min_j")]
    public double? WbalMinJ { get; set; }

    [JsonPropertyName("wbal_usage_pct")]
    public double? WbalUsagePct { get; set; }

    [JsonPropertyName("seconds_below_30pct")]
    public int? SecondsBelow30pct { get; set; }

    [JsonPropertyName("depletion_events")]
    public int? DepletionEvents { get; set; }

    [JsonPropertyName("recovery_ratio")]
    public double? RecoveryRatio { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class DayConstraintDto
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("training_allowed")]
    public bool? TrainingAllowed { get; set; }

    [JsonPropertyName("source_category")]
    public string? SourceCategory { get; set; }

    [JsonPropertyName("source_name")]
    public string? SourceName { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class FuelingActivityDto
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("duration_hours")]
    public double? DurationHours { get; set; }

    [JsonPropertyName("ride_type")]
    public string? RideType { get; set; }

    [JsonPropertyName("fueling_status")]
    public string? FuelingStatus { get; set; }

    [JsonPropertyName("carbs_per_hour")]
    public double? CarbsPerHour { get; set; }

    [JsonPropertyName("fueling_ratio")]
    public double? FuelingRatio { get; set; }

    [JsonPropertyName("carbs_classification")]
    public string? CarbsClassification { get; set; }

    [JsonPropertyName("ratio_classification")]
    public string? RatioClassification { get; set; }

    [JsonPropertyName("is_long_ride")]
    public bool? IsLongRide { get; set; }

    [JsonPropertyName("flags")]
    public List<string>? Flags { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class FuelingAnalysisDto
{
    [JsonPropertyName("week_starting")]
    public string? WeekStarting { get; set; }

    [JsonPropertyName("current_date")]
    public string? CurrentDate { get; set; }

    [JsonPropertyName("activities")]
    public List<FuelingActivityDto>? Activities { get; set; }

    [JsonPropertyName("weekly_summary")]
    public FuelingWeeklySummaryDto? WeeklySummary { get; set; }

    [JsonPropertyName("recommendations")]
    public List<string>? Recommendations { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class FuelingFormAnalysisDto
{
    [JsonPropertyName("fatigue_status")]
    public string? FatigueStatus { get; set; }

    [JsonPropertyName("fueling_status")]
    public string? FuelingStatus { get; set; }

    [JsonPropertyName("avg_carbs_per_hour")]
    public double? AvgCarbsPerHour { get; set; }

    [JsonPropertyName("avg_fueling_ratio")]
    public double? AvgFuelingRatio { get; set; }

    [JsonPropertyName("underfueled_sessions")]
    public int? UnderfueledSessions { get; set; }

    [JsonPropertyName("number_of_long_rides")]
    public int? NumberOfLongRides { get; set; }

    [JsonPropertyName("durability_limited_by_fueling")]
    public bool? DurabilityLimitedByFueling { get; set; }

    [JsonPropertyName("interpretation")]
    public string? Interpretation { get; set; }

    [JsonPropertyName("recommendation")]
    public string? Recommendation { get; set; }

    [JsonPropertyName("long_ride_advice")]
    public string? LongRideAdvice { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class FuelingWeeklySummaryDto
{
    [JsonPropertyName("number_of_long_rides")]
    public int? NumberOfLongRides { get; set; }

    [JsonPropertyName("avg_carbs_per_hour")]
    public double? AvgCarbsPerHour { get; set; }

    [JsonPropertyName("avg_fueling_ratio")]
    public double? AvgFuelingRatio { get; set; }

    [JsonPropertyName("number_of_underfueled_sessions")]
    public int? NumberOfUnderfueledSessions { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class IntervalSegmentDto
{
    [JsonPropertyName("start_time")]
    public int? StartTime { get; set; }

    [JsonPropertyName("end_time")]
    public int? EndTime { get; set; }

    [JsonPropertyName("elapsed_time")]
    public int? ElapsedTime { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("label")]
    public string? Label { get; set; }

    [JsonPropertyName("avg_power")]
    public double? AvgPower { get; set; }

    [JsonPropertyName("avg_hr")]
    public double? AvgHr { get; set; }

    [JsonPropertyName("max_hr")]
    public double? MaxHr { get; set; }

    [JsonPropertyName("intensity_pct")]
    public double? IntensityPct { get; set; }

    [JsonPropertyName("zone")]
    public int? Zone { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class MetricsDto
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("ftp")]
    public double? Ftp { get; set; }

    [JsonPropertyName("rolling_ftp")]
    public double? RollingFtp { get; set; }

    [JsonPropertyName("w_prime")]
    public double? WPrime { get; set; }

    [JsonPropertyName("rolling_w_prime")]
    public double? RollingWPrime { get; set; }

    [JsonPropertyName("rolling_p_max")]
    public double? RollingPMax { get; set; }

    [JsonPropertyName("lthr")]
    public double? Lthr { get; set; }

    [JsonPropertyName("max_hr")]
    public double? MaxHr { get; set; }

    [JsonPropertyName("weight")]
    public double? Weight { get; set; }

    [JsonPropertyName("age")]
    public int? Age { get; set; }

    [JsonPropertyName("sex")]
    public string? Sex { get; set; }

    [JsonPropertyName("ctl")]
    public double? Ctl { get; set; }

    [JsonPropertyName("atl")]
    public double? Atl { get; set; }

    [JsonPropertyName("resting_hr")]
    public double? RestingHr { get; set; }

    [JsonPropertyName("hrv")]
    public double? Hrv { get; set; }

    [JsonPropertyName("eftp")]
    public double? Eftp { get; set; }

    [JsonPropertyName("w_prime_wellness")]
    public double? WPrimeWellness { get; set; }

    [JsonPropertyName("sleep_secs")]
    public int? SleepSecs { get; set; }

    [JsonPropertyName("sleep_quality")]
    public string? SleepQuality { get; set; }

    [JsonPropertyName("wellness_trends")]
    public WellnessTrendsDto? WellnessTrends { get; set; }

    [JsonPropertyName("power_profile")]
    public PowerProfileDto? PowerProfile { get; set; }

    [JsonPropertyName("vo2max")]
    public double? Vo2max { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PlannedWorkoutEntryDto
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("time")]
    public string? Time { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("tags")]
    public List<string>? Tags { get; set; }

    [JsonPropertyName("duration_hours")]
    public double? DurationHours { get; set; }

    [JsonPropertyName("planned_load")]
    public double? PlannedLoad { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("zone_distribution")]
    public ZoneDistributionDto? ZoneDistribution { get; set; }

    [JsonPropertyName("steps")]
    public List<PlannedWorkoutStepDto>? Steps { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PlannedWorkoutStepDto
{
    [JsonPropertyName("duration_min")]
    public double? DurationMin { get; set; }

    [JsonPropertyName("power_pct_ftp")]
    public double? PowerPctFtp { get; set; }

    [JsonPropertyName("power_watts")]
    public double? PowerWatts { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PlannedWorkoutsDto
{
    [JsonPropertyName("generated_on")]
    public string? GeneratedOn { get; set; }

    [JsonPropertyName("current_week")]
    public PlannedWorkoutsWeekDto? CurrentWeek { get; set; }

    [JsonPropertyName("next_week")]
    public PlannedWorkoutsWeekDto? NextWeek { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PlannedWorkoutsWeekDto
{
    [JsonPropertyName("week_starting")]
    public string? WeekStarting { get; set; }

    [JsonPropertyName("planned_workouts")]
    public List<PlannedWorkoutEntryDto>? PlannedWorkouts { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PowerProfileDto
{
    [JsonPropertyName("p15s")]
    public PowerProfilePointDto? P15s { get; set; }

    [JsonPropertyName("p30s")]
    public PowerProfilePointDto? P30s { get; set; }

    [JsonPropertyName("p1min")]
    public PowerProfilePointDto? P1min { get; set; }

    [JsonPropertyName("p3min")]
    public PowerProfilePointDto? P3min { get; set; }

    [JsonPropertyName("p5min")]
    public PowerProfilePointDto? P5min { get; set; }

    [JsonPropertyName("p20min")]
    public PowerProfilePointDto? P20min { get; set; }

    [JsonPropertyName("curve_slope")]
    public double? CurveSlope { get; set; }

    [JsonPropertyName("period_days")]
    public int? PeriodDays { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class PowerProfilePointDto
{
    [JsonPropertyName("watts")]
    public double? Watts { get; set; }

    [JsonPropertyName("w_per_kg")]
    public double? WPerKg { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class TrainingPlanEntryDto
{
    [JsonPropertyName("week")]
    public string? Week { get; set; }

    [JsonPropertyName("plan_name")]
    public string? PlanName { get; set; }

    [JsonPropertyName("phase")]
    public string? Phase { get; set; }

    [JsonPropertyName("start")]
    public string? Start { get; set; }

    [JsonPropertyName("end")]
    public string? End { get; set; }

    [JsonPropertyName("phase_start")]
    public string? PhaseStart { get; set; }

    [JsonPropertyName("phase_end")]
    public string? PhaseEnd { get; set; }

    [JsonPropertyName("weekly_load_target")]
    public double? WeeklyLoadTarget { get; set; }

    [JsonPropertyName("week_type")]
    public string? WeekType { get; set; }

    [JsonPropertyName("week_note")]
    public string? WeekNote { get; set; }

    [JsonPropertyName("day_constraints")]
    public List<DayConstraintDto>? DayConstraints { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class WeatherDto
{
    [JsonPropertyName("average_weather_temp")]
    public double? AverageWeatherTemp { get; set; }

    [JsonPropertyName("average_feels_like")]
    public double? AverageFeelsLike { get; set; }

    [JsonPropertyName("max_rain")]
    public double? MaxRain { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class WeekSummaryDto
{
    [JsonPropertyName("week_starting")]
    public string? WeekStarting { get; set; }

    [JsonPropertyName("current_date")]
    public string? CurrentDate { get; set; }

    [JsonPropertyName("total_training_load")]
    public double? TotalTrainingLoad { get; set; }

    [JsonPropertyName("number_of_rides")]
    public int? NumberOfRides { get; set; }

    [JsonPropertyName("total_time_hours")]
    public double? TotalTimeHours { get; set; }

    [JsonPropertyName("longest_ride_hours")]
    public double? LongestRideHours { get; set; }

    [JsonPropertyName("vo2_sessions")]
    public int? Vo2Sessions { get; set; }

    [JsonPropertyName("threshold_sessions")]
    public int? ThresholdSessions { get; set; }

    [JsonPropertyName("long_ride_sessions")]
    public int? LongRideSessions { get; set; }

    [JsonPropertyName("endurance_sessions")]
    public int? EnduranceSessions { get; set; }

    [JsonPropertyName("avg_decoupling")]
    public double? AvgDecoupling { get; set; }

    [JsonPropertyName("avg_decoupling_label")]
    public string? AvgDecouplingLabel { get; set; }

    [JsonPropertyName("high_decoupling_rides")]
    public int? HighDecouplingRides { get; set; }

    [JsonPropertyName("form_absolute")]
    public double? FormAbsolute { get; set; }

    [JsonPropertyName("form_pct")]
    public double? FormPct { get; set; }

    [JsonPropertyName("form_percent_display")]
    public double? FormPercentDisplay { get; set; }

    [JsonPropertyName("form_zone")]
    public string? FormZone { get; set; }

    [JsonPropertyName("fueling_form_analysis")]
    public FuelingFormAnalysisDto? FuelingFormAnalysis { get; set; }

    [JsonPropertyName("training_plan")]
    public List<TrainingPlanEntryDto>? TrainingPlan { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class WellnessTrendDto
{
    [JsonPropertyName("current")]
    public double? Current { get; set; }

    [JsonPropertyName("avg_7d")]
    public double? Avg7d { get; set; }

    [JsonPropertyName("avg_prev_7d")]
    public double? AvgPrev7d { get; set; }

    [JsonPropertyName("trend_7d")]
    public string? Trend7d { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class WellnessTrendsDto
{
    [JsonPropertyName("weight")]
    public WellnessTrendDto? Weight { get; set; }

    [JsonPropertyName("resting_hr")]
    public WellnessTrendDto? RestingHr { get; set; }

    [JsonPropertyName("hrv")]
    public WellnessTrendDto? Hrv { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}

public class ZoneDistributionDto
{
    [JsonPropertyName("z1_z2_pct")]
    public double? Z1Z2Pct { get; set; }

    [JsonPropertyName("z3_z4_pct")]
    public double? Z3Z4Pct { get; set; }

    [JsonPropertyName("z5_plus_pct")]
    public double? Z5PlusPct { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extra { get; set; }
}
