using TrainingArchitect.Core.Models;

namespace TrainingArchitect.Core.Interfaces;

/// <summary>
/// Repository interface for <see cref="UsageCounter"/> documents.
/// </summary>
public interface IUsageCounterRepository : IRepository<UsageCounter>
{
    /// <summary>
    /// Records one usage event and increments both the monthly and ISO-weekly counters.
    /// </summary>
    /// <param name="athleteId">Athlete identifier.</param>
    /// <param name="action">Action key, for example <c>assess_metrics</c>.</param>
    /// <param name="inputTokens">Input tokens consumed by the action.</param>
    /// <param name="cachedTokens">Cached input tokens consumed by the action.</param>
    /// <param name="outputTokens">Output tokens generated by the action.</param>
    Task RecordUsageAsync(
        string athleteId,
        string action,
        int inputTokens,
        int cachedTokens,
        int outputTokens);

    /// <summary>
    /// Returns all usage counters for one athlete across monthly and weekly periods.
    /// </summary>
    /// <param name="athleteId">Athlete identifier.</param>
    Task<IReadOnlyList<UsageCounter>> GetByAthleteIdAsync(string athleteId);

    /// <summary>
    /// Returns the monthly and weekly usage counters for a specific athlete and period keys.
    /// Uses direct point reads by known document IDs to minimize RU consumption.
    /// </summary>
    /// <param name="athleteId">Athlete identifier.</param>
    /// <param name="monthlyPeriodKey">Monthly period key in yyyy-MM format.</param>
    /// <param name="weeklyPeriodKey">Weekly period key in ISO format yyyy-Www.</param>
    Task<(UsageCounter? Monthly, UsageCounter? Weekly)> GetByAthleteAndPeriodsAsync(
        string athleteId,
        string monthlyPeriodKey,
        string weeklyPeriodKey);
}
