using TrainingArchitect.Core.Models;

namespace TrainingArchitect.Core.Interfaces;

/// <summary>
/// Repository interface for <see cref="UsageCounter"/> documents.
/// </summary>
public interface IUsageCounterRepository : IRepository<UsageCounter>
{
    /// <summary>
    /// Records one usage event and increments both the monthly and ISO-weekly counters.
    /// </summary>
    /// <param name="athleteId">Athlete identifier.</param>
    /// <param name="action">Action key, for example <c>assess_metrics</c>.</param>
    /// <param name="inputTokens">Input tokens consumed by the action.</param>
    /// <param name="cachedTokens">Cached input tokens consumed by the action.</param>
    /// <param name="outputTokens">Output tokens generated by the action.</param>
    Task RecordUsageAsync(
        string athleteId,
        string action,
        int inputTokens,
        int cachedTokens,
        int outputTokens);

    /// <summary>
    /// Returns all usage counters for one athlete across monthly and weekly periods.
    /// </summary>
    /// <param name="athleteId">Athlete identifier.</param>
    Task<IReadOnlyList<UsageCounter>> GetByAthleteIdAsync(string athleteId);
}
