<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
    <UserSecretsId>fa40f1dc-2f48-4607-96cc-57d370a8c1c2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrainingArchitect.Client\TrainingArchitect.Client.csproj" />
    <ProjectReference Include="..\TrainingArchitect.Core\TrainingArchitect.Core.csproj" />
    <ProjectReference Include="..\TrainingArchitect.Infrastructure\TrainingArchitect.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.*" />
    <PackageReference Include="Microsoft.Identity.Web" Version="*" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="*" />
    <PackageReference Include="Markdig" Version="0.37.*" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.*" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.*" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.*" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="*" />
    <PackageReference Include="Syncfusion.Blazor.RichTextEditor" Version="*" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="*" />
  </ItemGroup>

</Project>
